with: junifer.testing.registry

workdir: /tmp

datagrabber:
  kind: PatternDataladDataGrabber
  uri: https://github.com/OpenNeuroDatasets/ds003097.git
  patterns:
    VBM_GM:
      pattern: derivatives/fmriprep/{subject}/anat/{subject}_space-MNI152NLin2009cAsym_label-GM_probseg.nii.gz
      space: MNI152NLin2009cAsym
    VBM_WM:
      pattern: derivatives/fmriprep/{subject}/anat/{subject}_space-MNI152NLin2009cAsym_label-WM_probseg.nii.gz
      space: MNI152NLin2009cAsym
  replacements:
    - subject
  types:
    - VBM_GM
    - VBM_WM

markers:
  - name: Schaefer100x7_mean
    kind: ParcelAggregation
    parcellation: Schaefer100x7
    method: mean
  - name: Schaefer100x7_std
    kind: ParcelAggregation
    parcellation: Schaefer100x7
    method: std
  - name: Schaefer200x7_mean
    kind: ParcelAggregation
    parcellation: Schaefer200x7
    method: mean
  - name: Schaefer200x7_std
    kind: ParcelAggregation
    parcellation: Schaefer200x7
    method: std
  - name: Brainnetome246_mean
    kind: ParcelAggregation
    parcellation: Brainnetome246
    method: mean
  - name: Brainnetome246_std
    kind: ParcelAggregation
    parcellation: Brainnetome246
    method: std

storage:
  kind: HDF5FeatureStorage
  uri: "/ruta.hdf5"